### ISSUE TITLE
Not working in windows10.

### ISSUE THREAD

**Issue by debajyoti1990** [ColonelPhantom/lite-xl-tmt#13]
I copied the extracted tmt folder in plugins folder. It is giving error. Could you please verify ?

**Comment by ColonelPhantom** [comment]
It sounds like you installed tmt into DATADIR, not USERDIR. You can do two things:

1. Run the nightly version at https://github.com/ColonelPhantom/lite-xl-tmt/releases/tag/nightly
2. Install tmt into USERDIR. If you're running a portable install with a `data` folder next to the executable, create another folder `user` next to it, create a `plugins` directory in there, and then put tmt in there. So if your current path looks like `(whatever)/data/plugins/tmt/init.lua`, change it to `(whatever)/user/plugins/tmt/init.lua`.

Please let me know if this solves your issues!

**Comment by debajyoti1990** [comment]
Every time I am opening lite xl, the log file opens and there these 2 errors are on top. Terminal otherwise is fine given you have already mentioned in github that it does not support scrolling.
 ![image](https://user-images.githubusercontent.com/48386861/219268667-95ed2133-b84e-4147-a079-35cec6c54081.png)

**Comment by debajyoti1990** [comment]
I installed some other plugins also in the same user folder, all working fine. I tried removing the tmt folder also, same errors are there. Do I need to write the init.lua for user folder myself ?

Update : I copied the init.lua from data folder to user folder and now only 1 error pops up while opening the lite-xl, "can not create workspace directory, permission denied."

Update 2: all resolved after copying plugins to C:\Users\(username)\.config\lite-xl\plugins

**Comment by ColonelPhantom** [comment]
Yeah, those errors are related to putting the USERDIR in a read-only location. Glad to hear you fixed the issue!

**Comment by goyalyashpal** [comment]
> C:\Users(username).config\lite-xl\plugins

Use this in future :smiley: `%USERPROFILE%\.config\lite-xl\plugins` - this works in explorer
